local  :
  dsfv2 :
    title : CRSP Daily Stock File
    query : 10701520
    var [94]  :
      0	:	permno
      1	:	secinfostartdt
      2	:	secinfoenddt
      3	:	securitybegdt
      4	:	securityenddt
      5	:	securityhdrflg
      6	:	hdrcusip
      7	:	hdrcusip9
      8	:	cusip
      9	:	cusip9
      10	:	primaryexch
      11	:	conditionaltype
      12	:	exchangetier
      13	:	tradingstatusflg
      14	:	securitynm
      15	:	shareclass
      16	:	usincflg
      17	:	issuertype
      18	:	securitytype
      19	:	securitysubtype
      20	:	sharetype
      21	:	securityactiveflg
      22	:	delactiontype
      23	:	delstatustype
      24	:	delreasontype
      25	:	delpaymenttype
      26	:	ticker
      27	:	tradingsymbol
      28	:	permco
      29	:	siccd
      30	:	naics
      31	:	icbindustry
      32	:	issuernm
      33	:	yyyymmdd
      34	:	dlycaldt
      35	:	dlydelflg
      36	:	dlyprc
      37	:	dlyprcflg
      38	:	dlycap
      39	:	dlycapflg
      40	:	dlyprevprc
      41	:	dlyprevprcflg
      42	:	dlyprevdt
      43	:	dlyprevcap
      44	:	dlyprevcapflg
      45	:	dlyret
      46	:	dlyretx
      47	:	dlyreti
      48	:	dlyretmissflg
      49	:	dlyretdurflg
      50	:	dlyorddivamt
      51	:	dlynonorddivamt
      52	:	dlyfacprc
      53	:	dlydistretflg
      54	:	dlyvol
      55	:	dlyclose
      56	:	dlylow
      57	:	dlyhigh
      58	:	dlybid
      59	:	dlyask
      60	:	dlyopen
      61	:	dlynumtrd
      62	:	dlymmcnt
      63	:	dlyprcvol
      64	:	shrstartdt
      65	:	shrenddt
      66	:	shrout
      67	:	shrsource
      68	:	shrfactype
      69	:	shradrflg
      70	:	disexdt
      71	:	disseqnbr
      72	:	disordinaryflg
      73	:	distype
      74	:	disfreqtype
      75	:	dispaymenttype
      76	:	disdetailtype
      77	:	distaxtype
      78	:	disorigcurtype
      79	:	disdivamt
      80	:	disfacpr
      81	:	disfacshr
      82	:	disdeclaredt
      83	:	disrecorddt
      84	:	dispaydt
      85	:	dispermno
      86	:	dispermco
      87	:	nasdcompno
      88	:	nasdissuno
      89	:	vwretd
      90	:	vwretx
      91	:	ewretd
      92	:	ewretx
      93	:	sprtrn
    file	:	dsfv2
    library : crsp
    format : parquet
    qvar	:	permno
    start_dt  : 1925-12-31
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    keyvar	:	permno permco ticker hdrcusip
    datevar	:	dlycaldt
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file  : wrds_dsfv2_query
      library	:	crspa
      format	:	csv
      compress	:	gz
      data_dictionary_table	:	wrds_dsfv2_query
      data_dictionary_product	:	crsp_a_stock
  dsmi :
    title : CRSP Daily Stock Market Indexes (NYSE/AMEX/NASDAQ/ARCA)
    query  : 10701522
    var [15]:
      0	:	dlycaldt
      1	:	vwretd
      2	:	vwretx
      3	:	vwtotval
      4	:	vwusdval
      5	:	vwtotcnt
      6	:	vwusdcnt
      7	:	ewretd
      8	:	ewretx
      9	:	ewtotval
      10  :	ewusdval
      11	:	ewtotcnt
      12	:	ewusdcnt
      13	:	sprtrn
      14	:	spindx
    file  :	dsmi
    library : crsp
    format : parquet
    start_dt  : 1925-12-31
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    datevar	:	dlycaldt
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : wrds_dailyindexret_query
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	wrds_dailyindexret_query
      data_dictionary_product	:	crsp_a_stock
  msfv2 :
    title : CRSP Monthly Stock File
    query  : 10701548
    var [87] : 
      0	:	permno
      1	:	secinfostartdt
      2	:	secinfoenddt
      3	:	securitybegdt
      4	:	securityenddt
      5	:	securityhdrflg
      6	:	hdrcusip
      7	:	hdrcusip9
      8	:	cusip
      9	:	cusip9
      10	:	primaryexch
      11	:	conditionaltype
      12	:	exchangetier
      13	:	tradingstatusflg
      14	:	securitynm
      15	:	shareclass
      16	:	usincflg
      17	:	issuertype
      18	:	securitytype
      19	:	securitysubtype
      20	:	sharetype
      21	:	securityactiveflg
      22	:	delactiontype
      23	:	delstatustype
      24	:	delreasontype
      25	:	delpaymenttype
      26	:	ticker
      27	:	tradingsymbol
      28	:	permco
      29	:	siccd
      30	:	naics
      31	:	icbindustry
      32	:	issuernm
      33	:	yyyymm
      34	:	mthcaldt
      35	:	mthcompflg
      36	:	mthcompsubflg
      37	:	mthprc
      38	:	mthprcflg
      39	:	mthprcdt
      40	:	mthdtflg
      41	:	mthdelflg
      42	:	mthcap
      43	:	mthprevprc
      44	:	mthprevprcflg
      45	:	mthprevdt
      46	:	mthprevdtflg
      47	:	mthprevcap
      48	:	mthret
      49	:	mthretx
      50	:	mthretflg
      51	:	mthdiscnt
      52	:	mthvol
      53	:	mthvolflg
      54	:	mthprcvol
      55	:	mthfacshrflg
      56	:	mthprcvolmisscnt
      57	:	shrstartdt
      58	:	shrenddt
      59	:	shrout
      60	:	shrsource
      61	:	shrfactype
      62	:	shradrflg
      63	:	disexdt
      64	:	disseqnbr
      65	:	disordinaryflg
      66	:	distype
      67	:	disfreqtype
      68	:	dispaymenttype
      69	:	disdetailtype
      70	:	distaxtype
      71	:	disorigcurtype
      72	:	disdivamt
      73	:	disfacpr
      74	:	disfacshr
      75	:	disdeclaredt
      76	:	disrecorddt
      77	:	dispaydt
      78	:	dispermno
      79	:	dispermco
      80	:	nasdcompno
      81	:	nasdissuno
      82	:	vwretd
      83	:	vwretx
      84	:	ewretd
      85	:	ewretx
      86	:	sprtrn
    file  :	msfv2
    library : crsp
    format : parquet
    start_dt  : 1925-12-31
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    qvar	:	permno
    keyvar	:	permno permco ticker hdrcusip
    datevar	:	mthcaldt
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : wrds_msfv2_query
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	wrds_msfv2_query
      data_dictionary_product	:	crsp_a_stock
  msmi :
    title : CRSP Monthly Stock Market Indexes (NYSE/AMEX/NASDAQ/ARCA)
    query  : 10701549
    var	[15] :
      0	:	mthcaldt
      1	:	vwretd
      2	:	vwretx
      3	:	vwtotval
      4	:	vwusdval
      5	:	vwtotcnt
      6	:	vwusdcnt
      7	:	ewretd
      8	:	ewretx
      9	:	ewtotval
      10	:	ewusdval
      11	:	ewtotcnt
      12	:	ewusdcnt
      13	:	sprtrn
      14	:	spindx
    file  :	msmi
    library : crsp
    format : parquet
    start_dt  : 1925-12-31
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    datevar	:	mthcaldt
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : wrds_monthlyindexret_query
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	wrds_monthlyindexret_query
      data_dictionary_product	:	crsp_a_stock  
  names :
    title : CRSP Stock Events - Historical Descriptive Information
    query : 10701563
    var [24] : 
      0	:	permno
      1	:	hdrprimaryexch
      2	:	nasdissuno
      3	:	hdrsiccd
      4	:	permco
      5	:	secinfostartdt
      6	:	secinfoenddt
      7	:	securitybegdt
      8	:	securityenddt
      9	:	cusip
      10	:	ticker
      11	:	issuernm
      12	:	shareclass
      13	:	usincflg
      14	:	issuertype
      15	:	securitytype
      16	:	securitysubtype
      17	:	sharetype
      18	:	securityactiveflg
      19	:	siccd
      20	:	primaryexch
      21	:	tradingsymbol
      22	:	naics
      23	:	tradingstatusflg
    file  :	names
    library : crsp
    format  : parquet
    datef   : YYYY-MM-DD
    qvar	:	permno
    idvar	:	permno
    id_table	:	StkSecurityInfoHdr
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : wrds_names_query
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	wrds_names_query
      data_dictionary_product	:	crsp_a_stock
  stkdelists  :
    title : CRSP Delisting Information
    query  : 10701575
    var	[19] :
      0	:	permno
      1	:	delistingdt
      2	:	deldtprc
      3	:	deldtprcflg
      4	:	delactiontype
      5	:	delstatustype
      6	:	delreasontype
      7	:	delpaymenttype
      8	:	delpermno
      9	:	delpermco
      10	:	delret
      11	:	delretmisstype
      12	:	delnextdt
      13	:	delnextprc
      14	:	delnextprcflg
      15	:	delamtdt
      16	:	deldivamt
      17	:	deldistype
      18	:	deldlydt
    extra1 [3] :
      0	:	primaryexch
      1	:	nasdissuno
      2	:	siccd
    extra2 [5] :
      0	:	'GDR'
      1	:	'GEX'
      2	:	'GLI'
      3	:	'LOS'
      4	:	'MER'
    file  :	stkdelists
    library : crsp
    format : parquet
    start_dt  : 1926-02-24
    end_dt    : 2024-12-30
    datef   : YYYY-MM-DD
    qvar	:	permno
    idvar	:	permno
    keyvar	:	permno
    qvards	:	stksecurityinfohdr
    datevar	:	delistingdt
    id_table	:	stksecurityinfohdr
    extra2_op	:	in
    extra2_var	:	DelActionType
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : stkdelists
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	stkdelists
      data_dictionary_product	:	crsp_a_stock
  stkdistributions  :
    title : CRSP Distribution Information
    query  : 10701569
    var	[19] :
      0	:	permno
      1	:	disexdt
      2	:	disseqnbr
      3	:	disordinaryflg
      4	:	distype
      5	:	disfreqtype
      6	:	dispaymenttype
      7	:	disdetailtype
      8	:	distaxtype
      9	:	disorigcurtype
      10	:	disdivamt
      11	:	disfacpr
      12	:	disfacshr
      13	:	disdeclaredt
      14	:	disrecorddt
      15	:	dispaydt
      16	:	dispermno
      17	:	dispermco
      18	:	disamountsourcetype
    extra1 [3] :
      0	:	primaryexch
      1	:	nasdissuno
      2	:	siccd
    extra2 [10] :
      0	:	'CD'
      1	:	'CG'
      2	:	'CP'
      3	:	'FRS'
      4	:	'IN'
      5	:	'N/A'
      6	:	'ROC'
      7	:	'SD'
      8	:	'SP'
      9	:	'TSOO'
    file  :	stkdistributions
    library : crsp
    format : parquet
    start_dt  : 1926-01-04
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    qvar	:	permno
    idvar	:	permno
    datevar	:	disexdt
    id_table	:	stksecurityinfohdr
    extra2_op	:	in
    extra2_var	:	DisType
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : stkdistributions
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	stkdistributions
      data_dictionary_product	:	crsp_a_stock
  stksecurityinfohdr  :
    title : CRSP Stock Header Information
    query  : 10717239
    var [36] : 
      0	:	permno
      1	:	secinfostartdt
      2	:	secinfoenddt
      3	:	securitybegdt
      4	:	securityenddt
      5	:	securityhdrflg
      6	:	hdrcusip
      7	:	hdrcusip9
      8	:	cusip
      9	:	cusip9
      10	:	primaryexch
      11	:	conditionaltype
      12	:	exchangetier
      13	:	tradingstatusflg
      14	:	securitynm
      15	:	shareclass
      16	:	usincflg
      17	:	issuertype
      18	:	securitytype
      19	:	securitysubtype
      20	:	sharetype
      21	:	securityactiveflg
      22	:	delactiontype
      23	:	delstatustype
      24	:	delreasontype
      25	:	delpaymenttype
      26	:	ticker
      27	:	tradingsymbol
      28	:	permco
      29	:	siccd
      30	:	naics
      31	:	icbindustry
      32	:	uesindustry
      33	:	nasdcompno
      34	:	nasdissuno
      35	:	issuernm
    extra2 [7] :
      0	:	'A'
      1	:	'B'
      2	:	'I'
      3	:	'N'
      4	:	'Q'
      5	:	'R'
      6	:	'X'
    file  :	stksecurityinfohdr
    library : crsp
    format : parquet
    datef   : YYYY-MM-DD
    qvar	:	permno
    idvar	:	permno
    id_table	:	StkSecurityInfoHdr
    extra2_op	:	in
    extra2_var	:	primaryexch
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : StkSecurityInfoHdr
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	stksecurityinfohdr
      data_dictionary_product	:	crsp_a_stock
  stkshares :
    title : CRSP Share Outstanding Information
    query  : 10701556
    var [7] : 
      0	:	permno
      1	:	shrstartdt
      2	:	shrenddt
      3	:	shrout
      4	:	shrsource
      5	:	shrfactype
      6	:	shradrflg
    extra1 [3] :
      0	:	primaryexch
      1	:	nasdissuno
      2	:	siccd
    file  :	stkshares
    library : crsp
    format : parquet
    start_dt  : 1925-12-01
    end_dt    : 2024-12-31
    datef   : YYYY-MM-DD
    qvar	:	permno
    idvar	:	permno
    keyvar	:	permno
    datevar	:	shrstartdt
    id_table	:	stksecurityinfohdr
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : stkshares
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	stkshares
      data_dictionary_product	:	crsp_a_stock
  tfz_dly :
    title : CRSP Treasuries - Issue Descriptions and Daily Time Series
    query  : 10701519
    var [33] : 
      0	:	kytreasno
      1	:	crspid
      2	:	ifcpdtf
      3	:	iflwr
      4	:	itax
      5	:	itype
      6	:	iuniq
      7	:	iwhy
      8	:	iymcn
      9	:	tbankdt
      10	:	tcouprt
      11	:	tcusip
      12	:	tdatdt
      13	:	tfcaldt
      14	:	tfcpdt
      15	:	tfrgntgt
      16	:	tmatdt
      17	:	tnippy
      18	:	tnotice
      19	:	tstripelig
      20	:	tvalfc
      21	:	tdaccint
      22	:	tdask
      23	:	tdbid
      24	:	tdduratn
      25	:	tdnomprc
      26	:	tdnomprc_flg
      27	:	tdpdint
      28	:	tdpubout
      29	:	tdretnua
      30	:	tdsourcr
      31	:	tdtotout
      32	:	tdyld
    file  :	tfz_dly
    library : crsp
    format : parquet
    start_dt  : 1916-01-01
    end_dt    : 2025-01-01
    datef   : YYYY-MM-DD
    qvar	:	tfcaldt # CALDT
    datevar	:	tdatdt
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : tfz_dly
      library  :	crspa
      format   :	csv
      compress	:	gz
      data_dictionary_table	:	tfz_iss
      data_dictionary_product	:	crsp_a_treasuries
