wrds  :
  finratiofirm  :
    title : WRDS Financial Ratios Firm Level by WRDS (Beta)
    query  : 10713636
    var [73] : 
      0	:	permno
      1	:	gvkey
      2	:	cusip
      3	:	ticker
      4	:	dpr
      5	:	peg_trailing
      6	:	bm
      7	:	capei
      8	:	divyield
      9	:	evm
      10	:	pcf
      11	:	pe_exi
      12	:	pe_inc
      13	:	pe_op_basic
      14	:	pe_op_dil
      15	:	ps
      16	:	ptb
      17	:	efftax
      18	:	gprof
      19	:	aftret_eq
      20	:	aftret_equity
      21	:	aftret_invcapx
      22	:	gpm
      23	:	npm
      24	:	opmad
      25	:	opmbd
      26	:	pretret_earnat
      27	:	pretret_noa
      28	:	ptpm
      29	:	roa
      30	:	roce
      31	:	roe
      32	:	capital_ratio
      33	:	equity_invcap
      34	:	debt_invcap
      35	:	totdebt_invcap
      36	:	invt_act
      37	:	rect_act
      38	:	fcf_ocf
      39	:	ocf_lct
      40	:	cash_debt
      41	:	cash_lt
      42	:	cfm
      43	:	short_debt
      44	:	profit_lct
      45	:	curr_debt
      46	:	debt_ebitda
      47	:	dltt_be
      48	:	int_debt
      49	:	int_totdebt
      50	:	lt_debt
      51	:	lt_ppent
      52	:	de_ratio
      53	:	debt_assets
      54	:	debt_at
      55	:	debt_capital
      56	:	intcov
      57	:	intcov_ratio
      58	:	cash_conversion
      59	:	cash_ratio
      60	:	curr_ratio
      61	:	quick_ratio
      62	:	at_turn
      63	:	inv_turn
      64	:	pay_turn
      65	:	rect_turn
      66	:	sale_equity
      67	:	sale_invcap
      68	:	sale_nwc
      69	:	accrual
      70	:	rd_sale
      71	:	adv_sale
      72	:	staff_sale
    file  :	finratiofirm
    library : wrds
    format  : parquet
    start_dt  : 1970-01-31
    end_dt    : 2024-12-31
    datef : YYYY-MM-DD
    qvar	:	permno
    datevar	:	public_date
    data_dictionary_table	:
    data_dictionary_product	:
    wrds  :
      wrdsversion	:	3
      method	:	3
      file : finratiofirm
      library  : wrdsapps
      format   : csv
      compress	:
      data_dictionary_table	:	firm_ratio
      data_dictionary_product	:	wrdsapps_finratio
  finratioind :
    fama-french :
      title : WRDS Financial Ratios Industry Level by WRDS (Beta) (Fama-French 48 Industries)
      query  : 10713788
      var [72] : 
        0	:	indret_ew
        1	:	indret_vw
        2	:	nfirm
        3	:	dpr
        4	:	peg_trailing
        5	:	bm
        6	:	capei
        7	:	divyield
        8	:	evm
        9	:	pcf
        10	:	pe_exi
        11	:	pe_inc
        12	:	pe_op_basic
        13	:	pe_op_dil
        14	:	ps
        15	:	ptb
        16	:	efftax
        17	:	gprof
        18	:	aftret_eq
        19	:	aftret_equity
        20	:	aftret_invcapx
        21	:	gpm
        22	:	npm
        23	:	opmad
        24	:	opmbd
        25	:	pretret_earnat
        26	:	pretret_noa
        27	:	ptpm
        28	:	roa
        29	:	roce
        30	:	roe
        31	:	capital_ratio
        32	:	equity_invcap
        33	:	debt_invcap
        34	:	totdebt_invcap
        35	:	invt_act
        36	:	rect_act
        37	:	fcf_ocf
        38	:	ocf_lct
        39	:	cash_debt
        40	:	cash_lt
        41	:	cfm
        42	:	short_debt
        43	:	profit_lct
        44	:	curr_debt
        45	:	debt_ebitda
        46	:	dltt_be
        47	:	int_debt
        48	:	int_totdebt
        49	:	lt_debt
        50	:	lt_ppent
        51	:	de_ratio
        52	:	debt_assets
        53	:	debt_at
        54	:	debt_capital
        55	:	intcov
        56	:	intcov_ratio
        57	:	cash_conversion
        58	:	cash_ratio
        59	:	curr_ratio
        60	:	quick_ratio
        61	:	at_turn
        62	:	inv_turn
        63	:	pay_turn
        64	:	rect_turn
        65	:	sale_equity
        66	:	sale_invcap
        67	:	sale_nwc
        68	:	accrual
        69	:	rd_sale
        70	:	adv_sale
        71	:	staff_sale
      extra6	:	48
      extra7	:	median
      file    :	fama-french
      library : wrds
      format  : parquet
      start_dt  : 1970-01-31
      end_dt    : 2024-12-31
      datef : YYYY-MM-DD
      datevar	:	public_date
      data_dictionary_table	:
      data_dictionary_product	:
      wrds  :
        wrdsversion	:	3
        method	:	1
        file : finratioind
        library  :	wrdsapps
        format   :	csv
        compress	:	
        data_dictionary_table	:	firm_ratio
        data_dictionary_product	:	wrdsapps_finratio
    gics :
      title : WRDS Financial Ratios Industry Level by WRDS (Beta) (GIC 10 Sectors )
      query  : 10701610
      var [72] : 
        0	:	indret_ew
        1	:	indret_vw
        2	:	nfirm
        3	:	dpr
        4	:	peg_trailing
        5	:	bm
        6	:	capei
        7	:	divyield
        8	:	evm
        9	:	pcf
        10	:	pe_exi
        11	:	pe_inc
        12	:	pe_op_basic
        13	:	pe_op_dil
        14	:	ps
        15	:	ptb
        16	:	efftax
        17	:	gprof
        18	:	aftret_eq
        19	:	aftret_equity
        20	:	aftret_invcapx
        21	:	gpm
        22	:	npm
        23	:	opmad
        24	:	opmbd
        25	:	pretret_earnat
        26	:	pretret_noa
        27	:	ptpm
        28	:	roa
        29	:	roce
        30	:	roe
        31	:	capital_ratio
        32	:	equity_invcap
        33	:	debt_invcap
        34	:	totdebt_invcap
        35	:	invt_act
        36	:	rect_act
        37	:	fcf_ocf
        38	:	ocf_lct
        39	:	cash_debt
        40	:	cash_lt
        41	:	cfm
        42	:	short_debt
        43	:	profit_lct
        44	:	curr_debt
        45	:	debt_ebitda
        46	:	dltt_be
        47	:	int_debt
        48	:	int_totdebt
        49	:	lt_debt
        50	:	lt_ppent
        51	:	de_ratio
        52	:	debt_assets
        53	:	debt_at
        54	:	debt_capital
        55	:	intcov
        56	:	intcov_ratio
        57	:	cash_conversion
        58	:	cash_ratio
        59	:	curr_ratio
        60	:	quick_ratio
        61	:	at_turn
        62	:	inv_turn
        63	:	pay_turn
        64	:	rect_turn
        65	:	sale_equity
        66	:	sale_invcap
        67	:	sale_nwc
        68	:	accrual
        69	:	rd_sale
        70	:	adv_sale
        71	:	staff_sale
      extra6	:	gics
      extra7	:	median
      file    :	gics
      library : wrds
      format  : parquet
      start_dt  : 1970-01-31
      end_dt    : 2024-12-31
      datef : YYYY-MM-DD
      datevar	:	public_date
      data_dictionary_table	:
      data_dictionary_product	:
      wrds  :
        wrdsversion	:	3
        method	:	1
        file : finratioind
        library  :	wrdsapps
        format   :	csv
        compress	:	
        data_dictionary_table	:	firm_ratio
        data_dictionary_product	:	wrdsapps_finratio